// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/inbox.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 110380855;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ama_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<InboxHandle> crateApiInboxInboxHandleCreate({required String device});

  Future<String?> crateApiInboxInboxHandleGetData({
    required InboxHandle that,
    required String msgId,
    required String bindPath,
  });

  Future<List<CardView>> crateApiInboxInboxHandleListMessages({
    required InboxHandle that,
  });

  Future<String> crateApiInboxInboxHandlePush({
    required InboxHandle that,
    required String summary,
    required String a2UiJson,
  });

  Future<void> crateApiInboxInboxHandleRecordAction({
    required InboxHandle that,
    required String msgId,
    required String actionName,
    String? actionContextJson,
  });

  Future<void> crateApiInboxInboxHandleSetData({
    required InboxHandle that,
    required String msgId,
    required String bindPath,
    required String valueJson,
  });

  Stream<DocEvent> crateApiInboxInboxHandleWatch({required InboxHandle that});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_InboxHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_InboxHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_InboxHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<InboxHandle> crateApiInboxInboxHandleCreate({required String device}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(device, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInboxInboxHandleCreateConstMeta,
        argValues: [device],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInboxInboxHandleCreateConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_create",
        argNames: ["device"],
      );

  @override
  Future<String?> crateApiInboxInboxHandleGetData({
    required InboxHandle that,
    required String msgId,
    required String bindPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
            that,
            serializer,
          );
          sse_encode_String(msgId, serializer);
          sse_encode_String(bindPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInboxInboxHandleGetDataConstMeta,
        argValues: [that, msgId, bindPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInboxInboxHandleGetDataConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_get_data",
        argNames: ["that", "msgId", "bindPath"],
      );

  @override
  Future<List<CardView>> crateApiInboxInboxHandleListMessages({
    required InboxHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_card_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInboxInboxHandleListMessagesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInboxInboxHandleListMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_list_messages",
        argNames: ["that"],
      );

  @override
  Future<String> crateApiInboxInboxHandlePush({
    required InboxHandle that,
    required String summary,
    required String a2UiJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
            that,
            serializer,
          );
          sse_encode_String(summary, serializer);
          sse_encode_String(a2UiJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInboxInboxHandlePushConstMeta,
        argValues: [that, summary, a2UiJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInboxInboxHandlePushConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_push",
        argNames: ["that", "summary", "a2UiJson"],
      );

  @override
  Future<void> crateApiInboxInboxHandleRecordAction({
    required InboxHandle that,
    required String msgId,
    required String actionName,
    String? actionContextJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
            that,
            serializer,
          );
          sse_encode_String(msgId, serializer);
          sse_encode_String(actionName, serializer);
          sse_encode_opt_String(actionContextJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInboxInboxHandleRecordActionConstMeta,
        argValues: [that, msgId, actionName, actionContextJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInboxInboxHandleRecordActionConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_record_action",
        argNames: ["that", "msgId", "actionName", "actionContextJson"],
      );

  @override
  Future<void> crateApiInboxInboxHandleSetData({
    required InboxHandle that,
    required String msgId,
    required String bindPath,
    required String valueJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
            that,
            serializer,
          );
          sse_encode_String(msgId, serializer);
          sse_encode_String(bindPath, serializer);
          sse_encode_String(valueJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInboxInboxHandleSetDataConstMeta,
        argValues: [that, msgId, bindPath, valueJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInboxInboxHandleSetDataConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_set_data",
        argNames: ["that", "msgId", "bindPath", "valueJson"],
      );

  @override
  Stream<DocEvent> crateApiInboxInboxHandleWatch({required InboxHandle that}) {
    final sink = RustStreamSink<DocEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
              that,
              serializer,
            );
            sse_encode_StreamSink_doc_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiInboxInboxHandleWatchConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiInboxInboxHandleWatchConstMeta =>
      const TaskConstMeta(
        debugName: "InboxHandle_watch",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_InboxHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_InboxHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  InboxHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InboxHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  InboxHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InboxHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  InboxHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return InboxHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<DocEvent> dco_decode_StreamSink_doc_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  CardStatus dco_decode_card_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CardStatus.values[raw as int];
  }

  @protected
  CardView dco_decode_card_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CardView(
      id: dco_decode_String(arr[0]),
      summary: dco_decode_String(arr[1]),
      source: dco_decode_String(arr[2]),
      createdAt: dco_decode_u_64(arr[3]),
      a2UiJson: dco_decode_String(arr[4]),
      status: dco_decode_card_status(arr[5]),
    );
  }

  @protected
  DocEvent dco_decode_doc_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DocEvent(
      kind: dco_decode_String(arr[0]),
      msgId: dco_decode_opt_String(arr[1]),
      bindPath: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<CardView> dco_decode_list_card_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_card_view).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  InboxHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return InboxHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  InboxHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return InboxHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  InboxHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return InboxHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<DocEvent> sse_decode_StreamSink_doc_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  CardStatus sse_decode_card_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CardStatus.values[inner];
  }

  @protected
  CardView sse_decode_card_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_a2UiJson = sse_decode_String(deserializer);
    var var_status = sse_decode_card_status(deserializer);
    return CardView(
      id: var_id,
      summary: var_summary,
      source: var_source,
      createdAt: var_createdAt,
      a2UiJson: var_a2UiJson,
      status: var_status,
    );
  }

  @protected
  DocEvent sse_decode_doc_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_msgId = sse_decode_opt_String(deserializer);
    var var_bindPath = sse_decode_opt_String(deserializer);
    return DocEvent(kind: var_kind, msgId: var_msgId, bindPath: var_bindPath);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<CardView> sse_decode_list_card_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CardView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_card_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    InboxHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as InboxHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    InboxHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as InboxHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerInboxHandle(
    InboxHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as InboxHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_doc_event_Sse(
    RustStreamSink<DocEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_doc_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_card_status(CardStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_card_view(CardView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_String(self.a2UiJson, serializer);
    sse_encode_card_status(self.status, serializer);
  }

  @protected
  void sse_encode_doc_event(DocEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.msgId, serializer);
    sse_encode_opt_String(self.bindPath, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_card_view(
    List<CardView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_card_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class InboxHandleImpl extends RustOpaque implements InboxHandle {
  // Not to be used by end users
  InboxHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  InboxHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_InboxHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_InboxHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_InboxHandlePtr,
  );

  /// Read the current converged value at a card's data-model path as a JSON
  /// string, or `None` if unset locally yet.
  Future<String?> getData({required String msgId, required String bindPath}) =>
      RustLib.instance.api.crateApiInboxInboxHandleGetData(
        that: this,
        msgId: msgId,
        bindPath: bindPath,
      );

  /// All cards present in the local replica, newest first, each paired with
  /// its converged [`CardStatus`].
  Future<List<CardView>> listMessages() =>
      RustLib.instance.api.crateApiInboxInboxHandleListMessages(that: this);

  /// Push a new actionable card. `a2ui_json` is the A2UI message tree
  /// serialized as JSON; pass `"{}"` if you don't have one yet.
  Future<String> push({required String summary, required String a2UiJson}) =>
      RustLib.instance.api.crateApiInboxInboxHandlePush(
        that: this,
        summary: summary,
        a2UiJson: a2UiJson,
      );

  /// Record a fired A2UI action against a card. `action_name == "dismiss"`
  /// dismisses the card; any other name marks it actioned. `action_context_json`
  /// is the resolved A2UI action context (BoundValue map) as a JSON string, or
  /// `None`/empty when the action carried no context. Converges across devices.
  Future<void> recordAction({
    required String msgId,
    required String actionName,
    String? actionContextJson,
  }) => RustLib.instance.api.crateApiInboxInboxHandleRecordAction(
    that: this,
    msgId: msgId,
    actionName: actionName,
    actionContextJson: actionContextJson,
  );

  /// Write an A2UI data-model binding value for a card. `bind_path` is a JSON
  /// Pointer like `/contact/email`; `value_json` is the value serialized as
  /// JSON. Converges across devices (latest-writer-wins per path).
  Future<void> setData({
    required String msgId,
    required String bindPath,
    required String valueJson,
  }) => RustLib.instance.api.crateApiInboxInboxHandleSetData(
    that: this,
    msgId: msgId,
    bindPath: bindPath,
    valueJson: valueJson,
  );

  /// Live document changes, for refreshing the UI on remote (and local)
  /// writes. Each event names the touched key family (`message` / `state` /
  /// `data`), plus a coarse `tick` when a sync / content batch completes (the
  /// point at which freshly-synced remote content becomes readable). The Dart
  /// side fetches the actual value via [`get_data`] / [`list_messages`].
  Stream<DocEvent> watch() =>
      RustLib.instance.api.crateApiInboxInboxHandleWatch(that: this);
}
